### ISSUE TITLE
强名称签名后，无法加载

### ISSUE THREAD

**Issue by view21cy** [weianweigan/DuEDrawingControl#4]
在Wpf应用中。
把Dll添加强名称签名后，会报错。
“System.Windows.Markup.XamlParseException:“未能加载文件或程序集“DuEDrawingControl, PublicKeyToken=null”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)”
”。
如果都不强名称签名，就没有问题。

**Comment by weianweigan** [comment]
# 关于强命名

强命名程序集只能加载其他强命名程序集，这是一条规则，和本仓库没关系，详见[微软文档](https://learn.microsoft.com/zh-cn/dotnet/standard/library-guidance/strong-naming)

> 强命名不是大多数 .NET 应用程序所必需的，默认情况下不得执行强命名。

# 本库强命名

此仓库使用了EDrawing的API，但未显式引用其dll，而是采用了Dynamic类型，我不确定对此仓库的dll强命名会不会引发其他问题。

# 如何强命名

https://learn.microsoft.com/zh-cn/dotnet/standard/assembly/sign-strong-name

可以考虑在主程序强命名时，对其依赖的dll进行一起强命名，强命名使用dll就行，不需要依赖源码。
