### ISSUE TITLE
不能打包运行

### ISSUE THREAD

**Issue by zckang** [weianweigan/DuEDrawingControl#5]
visual studio 2022中建立一个C# .NET 8.0程序，可以调试，但是不能打包在别的电脑上运行，请指教。
[三维模型浏览器.zip](https://github.com/user-attachments/files/18023393/default.zip)

**Comment by weianweigan** [comment]
| 感谢使用 @zckang 

# 描述错误

* 当前是在net48下编译的；
* 使用用的是DuEdrawingControlPlus，不是本仓库的包；

# 错误原因

* **未在x64下编译，见Readme.md -> Usage -> Step3**

![屏幕截图 2024-12-05 214100](https://github.com/user-attachments/assets/c19de2ce-1a30-44a0-a53d-677daa5e51b9)

> 更改后运行

![屏幕截图 2024-12-05 213929](https://github.com/user-attachments/assets/bc900881-812d-4c89-80cc-12a4d5cb5e08)

# 隐私

注意当前上传文件包含了公司和大学信息；

**Comment by zckang** [comment]
本机上可以运行，我的意思是打包成EXE文件或者直接将Debug文件夹复制到其他电脑上不能运行，提示缺少注册类。

**Comment by weianweigan** [comment]
@zckang 其他电脑安装edrawing了吗？没有注册类大概率是这个原因。
